import type { SiteSettings, ServiceItem, PortfolioItem } from '../types';

// Built-in content. The site renders these instantly and they seed the database;
// once Supabase responds, the live values from the database replace them.

export const DEFAULT_SETTINGS: SiteSettings = {
  phone: '+91 82522 57405',
  whatsapp: '918252257405',
  email: 'digimarketive@gmail.com',
  address: 'Ghitorni, New Delhi - 110030',
  business_hours: 'Monday - Saturday: 9:30 AM - 7:30 PM',
  meta_pixel_id: '',
  ga4_id: '',
  maintenance_mode: false,
  announcement_active: true,
  announcement_text: 'Quarterly Growth Slots Open — Flat 15% Savings on Annual Digital Retainers',
  announcement_link: '/pricing',
};

export const DEFAULT_SERVICES: ServiceItem[] = [
  {
    id: 'srv-1',
    name: 'Website Design & Development',
    slug: 'website-design-development',
    short_description: 'High-speed, conversion-focused websites, landing pages, and enterprise web solutions.',
    starting_price: 3499,
    icon: 'Globe',
    features: ['Modern UI/UX', 'Mobile Responsive', 'SEO Optimized', 'Speed Tuned', 'Lead Capture Funnels'],
    display_order: 1,
    is_active: true,
  },
  {
    id: 'srv-2',
    name: 'Creative Design',
    slug: 'creative-design',
    short_description: 'High-impact social media creatives, promotional posters, and ad designs.',
    starting_price: 119,
    icon: 'Palette',
    features: ['Custom Visuals', 'High Click-Through Design', 'Brand Typography', 'Ad Formats', 'Fast Turnaround'],
    display_order: 2,
    is_active: true,
  },
  {
    id: 'srv-3',
    name: 'Video Editing & Reels',
    slug: 'video-editing-reels',
    short_description: 'Dynamic short-form video, Instagram reels, motion captions, and direct-response hooks.',
    starting_price: 399,
    icon: 'Video',
    features: ['Hook Scripting', 'Dynamic Captions', 'Sound Design & SFX', 'Color Grading', 'Viral Pacing'],
    display_order: 3,
    is_active: true,
  },
  {
    id: 'srv-4',
    name: 'Social Media Management',
    slug: 'social-media-management',
    short_description: 'Organic brand presence, strategic content calendars, reels, stories, and engagement.',
    starting_price: 7999,
    icon: 'Share2',
    features: ['12-20 Monthly Posts', 'Reels & Stories', 'Hashtag & Caption Strategy', 'Monthly Analytics', 'Community Moderation'],
    display_order: 4,
    is_active: true,
  },
  {
    id: 'srv-5',
    name: 'Meta Ads Management',
    slug: 'meta-ads-management',
    short_description: 'High-ROAS Facebook & Instagram campaigns, custom audiences, retargeting & scaling.',
    starting_price: 5999,
    icon: 'Target',
    features: ['Ad Account Setup', 'Audience Research', 'A/B Creative Testing', 'Pixel Integration', 'Weekly Optimization'],
    display_order: 5,
    is_active: true,
  },
  {
    id: 'srv-6',
    name: 'Lead Generation',
    slug: 'lead-generation',
    short_description: 'High-intent B2B & B2C customer acquisition funnels that convert visitors into qualified leads.',
    starting_price: 11999,
    icon: 'Users',
    features: ['Custom Funnels', 'Instant WhatsApp Alerts', 'CRM Synchronization', 'Automated Qualification', 'Scalable Volume'],
    display_order: 6,
    is_active: true,
  },
  {
    id: 'srv-7',
    name: 'Google Ads',
    slug: 'google-ads',
    short_description: 'High-intent search ads, Performance Max campaigns, and display retargeting.',
    starting_price: 3499,
    icon: 'Search',
    features: ['Search Keyword Research', 'P-Max Campaigns', 'Negative Keyword Lists', 'Conversion Tracking', 'ROI Focus'],
    display_order: 7,
    is_active: true,
  },
  {
    id: 'srv-8',
    name: 'Google Business Profile',
    slug: 'google-business-profile',
    short_description: 'Rank #1 on Google Maps for local searches, review strategies, and direct lead calls.',
    starting_price: 1199,
    icon: 'MapPin',
    features: ['Profile Optimization', 'Local Geotagging', 'Review Generation Strategy', 'Weekly Posts', 'Call Tracking'],
    display_order: 8,
    is_active: true,
  },
  {
    id: 'srv-9',
    name: 'Local Business Marketing',
    slug: 'local-business-marketing',
    short_description: 'Hyper-local advertising, WhatsApp inquiries, and local discovery campaigns.',
    starting_price: 9499,
    icon: 'Store',
    features: ['Hyper-Local Geo Ads', 'Google Maps Boost', 'Local WhatsApp Marketing', 'Community Engagement', 'Store Footfall'],
    display_order: 9,
    is_active: true,
  },
  {
    id: 'srv-10',
    name: 'Branding & Identity',
    slug: 'branding-identity',
    short_description: 'Complete brand books, logos, color systems, stationery, and vector guidelines.',
    starting_price: 3499,
    icon: 'Sparkles',
    features: ['Logo Suite & Vectors', 'Color Palette & Typography', 'Stationery Kit', 'Social Media Kit', 'Brand Usage Guidelines'],
    display_order: 10,
    is_active: true,
  },
  {
    id: 'srv-11',
    name: 'Search Engine Optimization (SEO)',
    slug: 'seo',
    short_description: 'Technical SEO, on-page optimization, local maps ranking, and organic traffic growth.',
    starting_price: 5999,
    icon: 'TrendingUp',
    features: ['Keyword Analysis', 'Technical Audits', 'On-Page Optimization', 'Backlink Strategy', 'Monthly Rank Reports'],
    display_order: 11,
    is_active: true,
  },
  {
    id: 'srv-12',
    name: 'Marketing Automation',
    slug: 'marketing-automation',
    short_description: 'Automated WhatsApp routing, lead sync, email workflows, and CRM pipelines.',
    starting_price: 5999,
    icon: 'Cpu',
    features: ['WhatsApp Auto-Replies', 'CRM Webhook Integrations', 'Lead Notification Bots', 'Zero Manual Entry', 'Instant Speed to Lead'],
    display_order: 12,
    is_active: true,
  },
  {
    id: 'srv-13',
    name: 'WhatsApp Marketing',
    slug: 'whatsapp-marketing',
    short_description: 'Official WhatsApp template broadcasts, segmentation, and automated customer journeys.',
    starting_price: 1199,
    icon: 'MessageCircle',
    features: ['Meta Verified Templates', 'Segmented Broadcasts', 'Interactive CTA Buttons', 'Opt-In Lists', 'High Open Rates (98%)'],
    display_order: 13,
    is_active: true,
  },
  {
    id: 'srv-14',
    name: 'Content Writing',
    slug: 'content-writing',
    short_description: 'Persuasive ad copy, website copy, sales letters, and SEO-optimized blogs.',
    starting_price: 119,
    icon: 'PenTool',
    features: ['Direct Response Copy', 'High-CTR Ad Copy', 'Website Page Copy', 'SEO Blog Articles', 'Tone-of-Voice Alignment'],
    display_order: 14,
    is_active: true,
  },
  {
    id: 'srv-15',
    name: 'Website Maintenance',
    slug: 'website-maintenance',
    short_description: 'Regular backups, SSL security, speed optimization, uptime checks, and content updates.',
    starting_price: 1199,
    icon: 'ShieldCheck',
    features: ['Automated Backups', 'SSL & Security Audits', 'Speed & Cache Tuning', 'Content Updates', 'Fast Support Turnaround'],
    display_order: 15,
    is_active: true,
  },
];

export const DEFAULT_PORTFOLIO: PortfolioItem[] = [
  {
    id: 'port-3',
    title: 'NVA Infracon Corporate Infrastructure Portal',
    category: 'Websites',
    client: 'NVA Infracon',
    description: 'Modern infrastructure corporate portal, commercial civil construction project showcases, and dynamic procurement funnels.',
    image: '/nva-infracon.png',
    project_url: 'https://nvainfracon.com',
    is_featured: true,
    is_published: true,
    display_order: 1,
  }
];
