-- Initial website content (services, portfolio, site settings).
-- Existing rows are left untouched so edits made in the admin portal are never overwritten.

insert into public.site_settings (id, data) values (1, '{"phone":"+91 82522 57405","whatsapp":"918252257405","email":"digimarketive@gmail.com","address":"Ghitorni, New Delhi - 110030","business_hours":"Monday - Saturday: 9:30 AM - 7:30 PM","meta_pixel_id":"","ga4_id":"","maintenance_mode":false,"announcement_active":true,"announcement_text":"Quarterly Growth Slots Open — Flat 15% Savings on Annual Digital Retainers","announcement_link":"/pricing"}'::jsonb)
on conflict (id) do nothing;

insert into public.services (id, name, slug, short_description, starting_price, icon, features, display_order, is_active) values ('srv-1', 'Website Design & Development', 'website-design-development', 'High-speed, conversion-focused websites, landing pages, and enterprise web solutions.', 3499, 'Globe', '["Modern UI/UX","Mobile Responsive","SEO Optimized","Speed Tuned","Lead Capture Funnels"]'::jsonb, 1, true) on conflict (id) do nothing;
insert into public.services (id, name, slug, short_description, starting_price, icon, features, display_order, is_active) values ('srv-2', 'Creative Design', 'creative-design', 'High-impact social media creatives, promotional posters, and ad designs.', 119, 'Palette', '["Custom Visuals","High Click-Through Design","Brand Typography","Ad Formats","Fast Turnaround"]'::jsonb, 2, true) on conflict (id) do nothing;
insert into public.services (id, name, slug, short_description, starting_price, icon, features, display_order, is_active) values ('srv-3', 'Video Editing & Reels', 'video-editing-reels', 'Dynamic short-form video, Instagram reels, motion captions, and direct-response hooks.', 399, 'Video', '["Hook Scripting","Dynamic Captions","Sound Design & SFX","Color Grading","Viral Pacing"]'::jsonb, 3, true) on conflict (id) do nothing;
insert into public.services (id, name, slug, short_description, starting_price, icon, features, display_order, is_active) values ('srv-4', 'Social Media Management', 'social-media-management', 'Organic brand presence, strategic content calendars, reels, stories, and engagement.', 7999, 'Share2', '["12-20 Monthly Posts","Reels & Stories","Hashtag & Caption Strategy","Monthly Analytics","Community Moderation"]'::jsonb, 4, true) on conflict (id) do nothing;
insert into public.services (id, name, slug, short_description, starting_price, icon, features, display_order, is_active) values ('srv-5', 'Meta Ads Management', 'meta-ads-management', 'High-ROAS Facebook & Instagram campaigns, custom audiences, retargeting & scaling.', 5999, 'Target', '["Ad Account Setup","Audience Research","A/B Creative Testing","Pixel Integration","Weekly Optimization"]'::jsonb, 5, true) on conflict (id) do nothing;
insert into public.services (id, name, slug, short_description, starting_price, icon, features, display_order, is_active) values ('srv-6', 'Lead Generation', 'lead-generation', 'High-intent B2B & B2C customer acquisition funnels that convert visitors into qualified leads.', 11999, 'Users', '["Custom Funnels","Instant WhatsApp Alerts","CRM Synchronization","Automated Qualification","Scalable Volume"]'::jsonb, 6, true) on conflict (id) do nothing;
insert into public.services (id, name, slug, short_description, starting_price, icon, features, display_order, is_active) values ('srv-7', 'Google Ads', 'google-ads', 'High-intent search ads, Performance Max campaigns, and display retargeting.', 3499, 'Search', '["Search Keyword Research","P-Max Campaigns","Negative Keyword Lists","Conversion Tracking","ROI Focus"]'::jsonb, 7, true) on conflict (id) do nothing;
insert into public.services (id, name, slug, short_description, starting_price, icon, features, display_order, is_active) values ('srv-8', 'Google Business Profile', 'google-business-profile', 'Rank #1 on Google Maps for local searches, review strategies, and direct lead calls.', 1199, 'MapPin', '["Profile Optimization","Local Geotagging","Review Generation Strategy","Weekly Posts","Call Tracking"]'::jsonb, 8, true) on conflict (id) do nothing;
insert into public.services (id, name, slug, short_description, starting_price, icon, features, display_order, is_active) values ('srv-9', 'Local Business Marketing', 'local-business-marketing', 'Hyper-local advertising, WhatsApp inquiries, and local discovery campaigns.', 9499, 'Store', '["Hyper-Local Geo Ads","Google Maps Boost","Local WhatsApp Marketing","Community Engagement","Store Footfall"]'::jsonb, 9, true) on conflict (id) do nothing;
insert into public.services (id, name, slug, short_description, starting_price, icon, features, display_order, is_active) values ('srv-10', 'Branding & Identity', 'branding-identity', 'Complete brand books, logos, color systems, stationery, and vector guidelines.', 3499, 'Sparkles', '["Logo Suite & Vectors","Color Palette & Typography","Stationery Kit","Social Media Kit","Brand Usage Guidelines"]'::jsonb, 10, true) on conflict (id) do nothing;
insert into public.services (id, name, slug, short_description, starting_price, icon, features, display_order, is_active) values ('srv-11', 'Search Engine Optimization (SEO)', 'seo', 'Technical SEO, on-page optimization, local maps ranking, and organic traffic growth.', 5999, 'TrendingUp', '["Keyword Analysis","Technical Audits","On-Page Optimization","Backlink Strategy","Monthly Rank Reports"]'::jsonb, 11, true) on conflict (id) do nothing;
insert into public.services (id, name, slug, short_description, starting_price, icon, features, display_order, is_active) values ('srv-12', 'Marketing Automation', 'marketing-automation', 'Automated WhatsApp routing, lead sync, email workflows, and CRM pipelines.', 5999, 'Cpu', '["WhatsApp Auto-Replies","CRM Webhook Integrations","Lead Notification Bots","Zero Manual Entry","Instant Speed to Lead"]'::jsonb, 12, true) on conflict (id) do nothing;
insert into public.services (id, name, slug, short_description, starting_price, icon, features, display_order, is_active) values ('srv-13', 'WhatsApp Marketing', 'whatsapp-marketing', 'Official WhatsApp template broadcasts, segmentation, and automated customer journeys.', 1199, 'MessageCircle', '["Meta Verified Templates","Segmented Broadcasts","Interactive CTA Buttons","Opt-In Lists","High Open Rates (98%)"]'::jsonb, 13, true) on conflict (id) do nothing;
insert into public.services (id, name, slug, short_description, starting_price, icon, features, display_order, is_active) values ('srv-14', 'Content Writing', 'content-writing', 'Persuasive ad copy, website copy, sales letters, and SEO-optimized blogs.', 119, 'PenTool', '["Direct Response Copy","High-CTR Ad Copy","Website Page Copy","SEO Blog Articles","Tone-of-Voice Alignment"]'::jsonb, 14, true) on conflict (id) do nothing;
insert into public.services (id, name, slug, short_description, starting_price, icon, features, display_order, is_active) values ('srv-15', 'Website Maintenance', 'website-maintenance', 'Regular backups, SSL security, speed optimization, uptime checks, and content updates.', 1199, 'ShieldCheck', '["Automated Backups","SSL & Security Audits","Speed & Cache Tuning","Content Updates","Fast Support Turnaround"]'::jsonb, 15, true) on conflict (id) do nothing;

insert into public.portfolio (id, title, category, client, description, image, project_url, is_featured, is_published, display_order) values ('port-3', 'NVA Infracon Corporate Infrastructure Portal', 'Websites', 'NVA Infracon', 'Modern infrastructure corporate portal, commercial civil construction project showcases, and dynamic procurement funnels.', '/nva-infracon.png', 'https://nvainfracon.com', true, true, 1) on conflict (id) do nothing;
