// Generates supabase/seed.sql from the built-in site content in src/lib/defaults.ts.
// Run with: node scripts/generate-seed.mts   (Node 22.18+ strips TypeScript types natively)
import { writeFileSync } from 'node:fs';
import { DEFAULT_SETTINGS, DEFAULT_SERVICES, DEFAULT_PORTFOLIO } from '../src/lib/defaults.ts';

const lit = (v: unknown): string => {
  if (v === undefined || v === null) return 'null';
  if (typeof v === 'number' || typeof v === 'boolean') return String(v);
  return `'${String(v).replace(/'/g, "''")}'`;
};
const json = (v: unknown) => `${lit(JSON.stringify(v))}::jsonb`;

const lines: string[] = [
  '-- Generated by scripts/generate-seed.mts — initial website content.',
  '-- Existing rows are left untouched so edits made in the admin portal are never overwritten.',
  '',
  `insert into public.site_settings (id, data) values (1, ${json(DEFAULT_SETTINGS)})`,
  'on conflict (id) do nothing;',
  '',
];

for (const s of DEFAULT_SERVICES) {
  lines.push(
    'insert into public.services (id, name, slug, short_description, starting_price, icon, features, display_order, is_active) values (' +
      [lit(s.id), lit(s.name), lit(s.slug), lit(s.short_description), lit(s.starting_price), lit(s.icon), json(s.features), lit(s.display_order), lit(s.is_active)].join(', ') +
      ') on conflict (id) do nothing;'
  );
}
lines.push('');

for (const p of DEFAULT_PORTFOLIO) {
  lines.push(
    'insert into public.portfolio (id, title, category, client, description, image, project_url, is_featured, is_published, display_order) values (' +
      [lit(p.id), lit(p.title), lit(p.category), lit(p.client), lit(p.description), lit(p.image), lit(p.project_url), lit(p.is_featured), lit(p.is_published), lit(p.display_order)].join(', ') +
      ') on conflict (id) do nothing;'
  );
}

writeFileSync(new URL('../supabase/seed.sql', import.meta.url), lines.join('\n') + '\n');
console.log(`seed.sql written: ${DEFAULT_SERVICES.length} services, ${DEFAULT_PORTFOLIO.length} portfolio items`);
